<?php

namespace Acme\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository{
    
    public function getUserLists($page = 1){
        return $this->getEntityManager()->createQuery("select u from AcmeUserBundle:User u")->getResult();
    }
    
}
