acme_user_homepage:
    pattern:  /user
    defaults: { _controller: AcmeUserBundle:Default:index }

acme_user_list:
    pattern:  /user/list/{page}
    defaults: { _controller: AcmeUserBundle:Default:list, page: 1 }

acme_user_user:
    pattern:  /user/info/{name}
    defaults: { _controller: AcmeUserBundle:Default:info }

acme_user_register:
    pattern: /user/register
    defaults: { _controller:AcmeUserBundle:Default:register }
